## Write a function in Python

In [1]:
def function_name (parameter):
    """Docstring should include a description of the function here 
       as well as identify the parameters (inputs) that the function 
       can take the return (ouput) provided by the function, 
       as shown below.
       
       Parameters
       ----------
       input:type
           Description of input.
        Returns
        ---------
        output:type
            Description of output
    """
    pass
    return output

In [2]:
def mm_to_in(mm):
    """
    Convert input from millimeters to inches.
    
    Parameters
    ----------
    mm:int or float
        Numeric value with units in mm
    
    Returns
    -------
    inches:int or float
        Numeric value with units in inches
    """
    inches = mm/25.4
    return inches

### Call custom functions in Python

In [3]:
precip_jan_mm = 17.78

mm_to_in(precip_jan_mm)

0.7000000000000001

In [7]:
# The original values of precip_jan_in has not been changed
precip_jan_mm

17.78

### Applying the same function to multiple object types

In [12]:
import numpy as np
import pandas as pd

In [6]:
avg_monthly_precip_mm = np.array([17.78, 19.05, 46.99, 74.422, 
                                 77.47, 51.308, 49.022, 41.148, 
                                 46.736, 33.274, 35.306, 21.336])
mm_to_in(avg_monthly_precip_mm)

array([0.7 , 0.75, 1.85, 2.93, 3.05, 2.02, 1.93, 1.62, 1.84, 1.31, 1.39,
       0.84])

In [11]:
precip_2002 = pd.DataFrame(columns = ['month', 'precip_mm'], 
                           data = [
                              ['Jan', 27.178], ['Feb', 11.176], 
                              ['Mar', 38.100], ['Apr', 5.080], 
                              ['May', 81.280], ['Jun', 29.972], 
                              ['Jul', 2.286], ['Aug', 36.576], 
                              ['Sep', 38.608], ['Oct', 61.976], 
                              ['Nov', 19.812], ['Dec', 0.508]
                           ])

In [13]:
precip_2002['precip_in'] = mm_to_in(mm = precip_2002['precip_mm'])
precip_2002

month  precip_mm  precip_in
0    Jan     27.178       1.07
1    Feb     11.176       0.44
2    Mar     38.100       1.50
3    Apr      5.080       0.20
4    May     81.280       3.20
5    Jun     29.972       1.18
6    Jul      2.286       0.09
7    Aug     36.576       1.44
8    Sep     38.608       1.52
9    Oct     61.976       2.44
10   Nov     19.812       0.78
11   Dec      0.508       0.02

### Call help on a custom function

In [14]:
help(np.mean)

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.

In [15]:
help(mm_to_in)

Help on function mm_to_in in module __main__:

mm_to_in(mm)
    Convert input from millimeters to inches.
    
    Parameters
    ----------
    mm:int or float
        Numeric value with units in mm
    
    Returns
    -------
    inches:int or float
        Numeric value with units in inches



### Combine multiple function calls on a single object in python

In [16]:
avg_monthly_precip_mean_in = np.mean(mm_to_in(mm = avg_monthly_precip_mm))
avg_monthly_precip_mean_in

1.6858333333333333

## Write functions with multiple parameters in python

### Call customs functions with multiple parameters in python

In [5]:
def multiply_values(x, y):
    """Calculate product of two imputs.
    Parameters
    ----------
    x: int or float
    y: int or float
    
    Returns
    -------
    ans: int or float
    """
    ans = print(round(x*y, 2))
    return ans

In [6]:
multiply_values(0.7, 25.4)

17.78


In [9]:
# Average monthly precip (inches) for Jan in Boulder, CO
precip_jan_in = 0.7

# Conversion factor from inches to millimeters
to_mm = 25.4

In [10]:
precip_jan_mm = multiply_values(x = precip_jan_in, y = to_mm)

17.78


### Combine unit conversion and calculation of statistics into one function

In [11]:
def mm_to_in(mm):
    '''Convert input from millimeters to inches.
    
    Parameters
    ----------
    mm: int or float
        numeric value with units in millimeters.
        
    Returns
    -------
    inches: int or float
        numeric value with units in inches.
    '''
    inches = mm/25.4
    return inches

You can expand this function to include running a mean along a specified axis for columns or rows and then use this function on many numpy arrays as needed. Begin by defining the function with a descriptive name and the two necessary parameters:
* the input array with values in millimeters
* the axis value for the mean calculation

In [23]:
def mean_mm_to_in_arr(arr_mm, axis_value):
    """Calculate mean values of input array along a specified axis and convert values from millimeters to inches.
    
    Parameters
    ----------
    arr_mm: numpy array
        numeric values in millimeters
    axis_value: int
    0 to calculate mean for each column
    1 to calculate mean for each row
    
    Returns
    -------
    mean_arr_in: numpy array
        mean values of input array in inches.
    """
    mean_arr_mm = np.mean(arr_mm, axis = axis_value)
    mean_arr_in = mean_arr_mm/25.4
    
    return mean_arr_in

In [25]:
# 2d array of average monthly precip(mm) for 2002 and 2013 in Boulder, CO
precip_2002_2013_mm = ([[27.178, 11.176, 38.1, 5.08, 81.28, 29.972, 
                        2.286, 36.576, 38.608, 61.976, 19.812, 0.508], 
                        [6.858, 28.702, 43.688, 105.156, 67.564, 15.494, 
                        26.162, 35.56, 461.264, 56.896, 7.366, 12.7]])

In [26]:
# Calculate monthly mean (inches) for precip_2002_2013
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_2013_mm, axis_value = 0)
monthly_mean_in

array([0.67 , 0.785, 1.61 , 2.17 , 2.93 , 0.895, 0.56 , 1.42 , 9.84 ,
       2.34 , 0.535, 0.26 ])

In [28]:
# Calculate yearly mean (inches) for precip_2002_2013
yearly_mean_in = mean_mm_to_in_arr(precip_2002_2013_mm, 1)
yearly_mean_in

array([1.15666667, 2.84583333])

### Define optional input parameters for a function

In [30]:
precip_2002_mm = np.array([27.178, 11.176, 38.1, 5.08, 81.28, 29.972, 
                          2.286, 36.576, 38.608, 61.976, 19.812, 0.508])

In [32]:
def mean_mm_to_in_arr(arr_mm, axis_value = None):
    """Calculate mean values of input array and convert values from millimeters to inches. If an axis is specified, the mean will be calculate alsong that axis.
    
    Parameters
    ----------
     arr_mm: numpy array
        numeric values in millimeters
    axis_value: int (optional)
        0 to calculate mean for each column
        1 to calculate mean for each row
    
    Returns
    -------
    mean_arr_in: numpy array
        mean values of input array in inches.
    """
    if axis_value == None:
        mean_arr_mm = np.mean(arr_mm)
    else:
        mean_arr_mm = np.mean(arr_mm, axis = axis_value)
    mean_arr_in = mean_arr_mm/25.4
    return mean_arr_in

In [38]:
import pandas as pd

In [36]:
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_2013_mm, axis_value = 0)
monthly_mean_in

array([0.67 , 0.785, 1.61 , 2.17 , 2.93 , 0.895, 0.56 , 1.42 , 9.84 ,
       2.34 , 0.535, 0.26 ])

In [33]:
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_mm)

monthly_mean_in

1.1566666666666667

### Combine download and import of data files into one function

In [44]:
def download_import_df(file_url, path):
    '''Download file from specified URL and import file into a pandas dataframe from a specified path.
    
    Working directroy is set to earth-analytics directory under home, which is automatically created by the download.
    
    Parameters
    ----------
    file_url: str
        URL to CSV file(http or https)
    path: str
        path to csv file using relative path to earth-analytics directory under home.
        
    Returns
    -------
    df: pandas dataframe
        data imported from downloaded csv file. 
    '''
    et.data.get_data(url = file_url)
    os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))
    df = pd.read_csv(path)
    
    return df
    

In [39]:
import os
import pandas as pd
import earthpy as et

In [46]:
precip_2002_2013_df_url = 'https://ndownloader.figshare.com/files/12710621'

precip_2002_2013_df_path = os.path.join('data', 'earthpy-downloads', 'precip-2002-2013-months-seasons.csv')

precip_2002_2013_df = download_import_df(
    file_url = precip_2002_2013_df_url, 
    path = precip_2002_2013_df_path)

precip_2002_2013_df

### Making functions more efficient does not always mean more parameters

In [48]:
def download_import_df(file_url):
    '''Download file from specified url and import file into a pandas dataframe.
    The pat to the download file is automatically generated by the download and is passed to the pandas function to create a new dataframe.
    
    Parameters
    ----------
    file_url: str
        url to csv file(http or https)
        
    Returns
    -------
    df: pandas dataframe
        Dataframe imported from a downloaded csv file.
    '''
    
    df = pd.read_csv(et.data.get_data(url = file_url))
    return df

In [49]:
precip_2002_2013_df = download_import_df(
    file_url = precip_2002_2013_df_url)
precip_2002_2013_df

months  precip_2002  precip_2013 seasons
0     Jan         1.07         0.27  Winter
1     Feb         0.44         1.13  Winter
2     Mar         1.50         1.72  Spring
3     Apr         0.20         4.14  Spring
4     May         3.20         2.66  Spring
5    June         1.18         0.61  Summer
6    July         0.09         1.03  Summer
7     Aug         1.44         1.40  Summer
8    Sept         1.52        18.16    Fall
9     Oct         2.44         2.24    Fall
10    Nov         0.78         0.29    Fall
11    Dec         0.02         0.50  Winter